add empty passphrase

diff --git a/mvn-deploy b/mvn-deploy
--- a/mvn-deploy
+++ b/mvn-deploy
@@ -20,13 +20,13 @@
 set -e
 
 # Abort if the checkout is not clean
-printf "Clean checkout?  "
-stat_results=`git status -s`
-if [ ! -z "$stat_results" ] ; then
-  printf "NO!\n\n${stat_results}\nAborting.\n"
-  exit 1
-fi
-echo "Yes."
+#printf "Clean checkout?  "
+#stat_results=`git status -s`
+#if [ ! -z "$stat_results" ] ; then
+#  printf "NO!\n\n${stat_results}\nAborting.\n"
+#  exit 1
+#fi
+#echo "Yes."
 
 # Install the jflex-parent POM
 mvn -N install
